default: &default
  adapter: sqlite3
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: db/development.sqlite3

development:
  <<: *default

test:
  <<: *default

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: Contentify_production
  username: Contentify
  password: <%= ENV['CONTENTIFY_DATABASE_PASSWORD'] %>
